name: Build

on:  
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        run: npm install

      - name: Integration tests
        run: npm test

      - name: Building
        run: npm run build
        env:
          REACT_APP_BASE_PATH: ${{ secrets.REACT_APP_BASE_PATH }}
          REACT_APP_ITUNES_API: ${{ secrets.REACT_APP_ITUNES_API }}
          REACT_APP_SENTRY_URL: ${{ secrets.REACT_APP_SENTRY_URL }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build