name: ITunes Top List CI

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        run: npm install

  test:
    name: Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Integration tests
        uses: actions/cache@v2
        run: npm test
      
    