name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        run: npm install

      - name: Integration tests
        run: npm test