name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: setup 🛠
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dependencies
          path: node_modules
          retention-days: 1

  test:
    name: test 🧪
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dependencies
          path: node_modules

      - name: Integration tests
        run: npm test

  