name: ITunes Top List Build

on: push

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - run: npm install


  test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - run: npm test

    
      